baseURL = "https://vorblock.cc/"
languageCode = "zh-CN"
title = "root@v"
theme = "vorblock"
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 10
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "manni"
googleAnalytics = "UA-140385231-1"
footnotereturnlinkcontents = "↩"
enableEmoji = true
[permalinks]
blog = "/blog/:year:month:day-:title/"
flight-rules = "/flight-rules/:year:month:day-:title/"

[params]
  name="vorblock"
  AuthorName = "vorblock"
  Description = "Are You OK?"
  images = [
      "https://vorblock.cc/favicon.svg",
      "https://my-md-1253484710.cos.ap-chengdu.myqcloud.com/tx.jpg"
  ]

[params.CDN]
#enable = false
enable = true
# Host must end with `/`
Host = "https://my-md-1253484710.cos.ap-chengdu.myqcloud.com/"

# [params.comments.isso]
# Host = "http://47.106.212.155:8080/"

[params.katex]
base = "https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/"
CSSintegrity="sha384-zB1R0rpPzHqg7Kpt0Aljp8JPLqbXI3bhnPWROx27a9N0Ll6ZP/+DiW/UqRcLbRjq"
JSIntegrity="sha384-y23I5Q6l+B6vatafAwxRu/0oK/79VlbSz7Q9aiSZUvyWYIYsd+qj+o24G5ZU2zJz"
AutoRenderIntegrity="sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI"

[blackfriday]
  hrefTargetBlank = true


[[menu.main]]
    name = "/POSTS/~"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "/TODO/~"
    url = "/todo/"
    weight = 3
# [[menu.main]]
#     name = "PAPER NOTES"
#     url = "/paper-notes/"
#     weight = 5
[[menu.main]]
    name = "/CATEGORIES/~"
    url = "/categories/"
    weight = 8
[[menu.main]]
    name = "/TAGS/~"
    url = "/tags/"
    weight = 9
[[menu.main]]
    name = "/ABOUT/~"
    url = "/about/"
    weight = 10
[[menu.main]]
    name = "/RSS"
    url = "/index.xml"